verbose: true

bot:
  name: dummy-bot
  version: 1.0
  email: paolo@codesake.com
  behaviour: dummy-bot.rb

twitter:
  enabled: no

task:
  - { schedule: every 5 s, action: say_hello }
  - { schedule: every 3 s, action: say_foo }
